version: "3.3"
services:
  selenium:
    image: selenium/standalone-firefox:latest
    shm_size: 2gb
    container_name: selenium 
    restart: always
    ports:
      - 5031:4444
      - 5032:7900 

